# RealSense camera configuration
realsense2_camera:
  ros__parameters:
    # Device configuration
    device_type: ""                    # Auto-detect device type
    serial_no: ""                      # Auto-detect serial number
    usb_port_id: ""                    # Auto-detect USB port
    
    # Stream configuration
    enable_depth: true
    enable_color: true
    enable_infra1: false               # Disable infrared streams to save bandwidth
    enable_infra2: false
    enable_fisheye: false
    
    # Stream profiles (resolution and framerate)
    depth_width: 640
    depth_height: 480
    depth_fps: 30
    
    color_width: 640
    color_height: 480
    color_fps: 30
    
    # Processing modules
    align_depth.enable: true           # Align depth to color
    spatial_filter.enable: true       # Enable spatial filtering
    temporal_filter.enable: true      # Enable temporal filtering
    hole_filling_filter.enable: true  # Fill holes in depth image
    decimation_filter.enable: false   # Disable decimation for better quality
    
    # Point cloud (disabled to save bandwidth)
    pointcloud.enable: false
    
    # Synchronization
    enable_sync: true                  # Synchronize depth and color streams
    
    # Quality of Service
    qos: "SENSOR_DATA"                 # Use sensor data QoS profile