#!/usr/bin/env python3
"""
Live Arm Calibration Script for LLMy Robot
Shows current arm positions in real-time and allows setting them as zero positions
"""

import rclpy
from rclpy.node import Node
from sensor_msgs.msg import JointState
import sys
import termios
import tty
import select
import math
import os


class ArmCalibrationTool(Node):
    def __init__(self):
        super().__init__('arm_calibration_tool')
        
        # Subscribe to joint states
        self.subscription = self.create_subscription(
            JointState,
            '/motor_manager/joint_states',
            self.joint_state_callback,
            10
        )
        
        # Store latest positions
        self.latest_positions = {}
        self.arm_joints = ["1", "2", "3", "4", "5", "6"]  # Arm joint names
        
        # Terminal setup for non-blocking input
        self.old_settings = termios.tcgetattr(sys.stdin)
        
        print("=== LLMy Arm Calibration Tool ===")
        print("This tool shows live arm positions and allows you to set current positions as zero.")
        print("Press ENTER to set current positions as zero, or 'q' to quit.")
        print("Waiting for joint states...")
        print("-" * 80)
        
    def joint_state_callback(self, msg):
        """Update stored positions and display them"""
        # Update positions for arm joints
        for i, name in enumerate(msg.name):
            if name in self.arm_joints and i < len(msg.position):
                self.latest_positions[name] = msg.position[i]
        
        # Display current positions
        self.display_positions()
    
    def display_positions(self):
        """Display current arm positions in a clean format"""
        # Clear screen and move cursor to top
        os.system('clear')
        
        print("=== LLMy Arm Calibration Tool ===")
        print("Current Arm Positions:")
        print("-" * 50)
        
        for joint in self.arm_joints:
            if joint in self.latest_positions:
                pos_rad = self.latest_positions[joint]
                pos_deg = math.degrees(pos_rad)
                # Convert to servo ticks for reference
                servo_center = 2048
                ticks_per_rev = 4096
                pos_ticks = int(servo_center + (pos_rad / (2.0 * math.pi)) * ticks_per_rev)
                
                print(f"Joint {joint}: {pos_rad:+7.3f} rad ({pos_deg:+7.1f}°) [{pos_ticks:4d} ticks]")
            else:
                print(f"Joint {joint}: No data")
        
        print("-" * 50)
        print("Press ENTER to set these positions as ZERO")
        print("Press 'q' to quit")
        print("-" * 50)
    
    def set_zero_positions(self):
        """Set current positions as zero by writing them to a calibration file"""
        if not self.latest_positions:
            print("ERROR: No joint positions received yet!")
            return
        
        # Check if we have all arm joints
        missing_joints = [joint for joint in self.arm_joints if joint not in self.latest_positions]
        if missing_joints:
            print(f"ERROR: Missing data for joints: {missing_joints}")
            return
        
        print("\n" + "="*50)
        print("SETTING CURRENT POSITIONS AS ZERO!")
        print("="*50)
        
        # Create calibration data
        calibration_data = {}
        for joint in self.arm_joints:
            pos_rad = self.latest_positions[joint]
            pos_deg = math.degrees(pos_rad)
            calibration_data[joint] = pos_rad
            print(f"Joint {joint}: {pos_rad:+7.3f} rad ({pos_deg:+7.1f}°) -> ZERO")
        
        # Write calibration file
        calibration_file = "/tmp/arm_calibration_offsets.txt"
        try:
            with open(calibration_file, 'w') as f:
                f.write("# Arm calibration offsets (radians)\n")
                f.write("# Generated by LLMy calibration tool\n")
                f.write("# Format: joint_name offset_radians\n")
                for joint, offset in calibration_data.items():
                    f.write(f"{joint} {offset:.6f}\n")
            
            print(f"\nCalibration offsets written to: {calibration_file}")
            print("\nNext steps:")
            print("1. Copy these offsets to your servo manager configuration")
            print("2. Restart the servo manager to apply the calibration")
            print("3. The current positions will now be treated as zero positions")
            
        except Exception as e:
            print(f"ERROR writing calibration file: {e}")
        
        print("\nPress any key to continue or 'q' to quit...")
    
    def run(self):
        """Main loop for the calibration tool"""
        try:
            tty.setraw(sys.stdin.fileno())
            
            while rclpy.ok():
                # Spin once to process callbacks
                rclpy.spin_once(self, timeout_sec=0.1)
                
                # Check for keyboard input
                if select.select([sys.stdin], [], [], 0) == ([sys.stdin], [], []):
                    key = sys.stdin.read(1)
                    
                    if key.lower() == 'q':
                        print("\nExiting calibration tool...")
                        break
                    elif key == '\r' or key == '\n':  # Enter key
                        self.set_zero_positions()
                        # Wait for another key press
                        print("Press any key to continue...")
                        sys.stdin.read(1)
                        
        except KeyboardInterrupt:
            print("\nCalibration tool interrupted.")
        finally:
            # Restore terminal settings
            termios.tcsetattr(sys.stdin, termios.TCSADRAIN, self.old_settings)
    
    def __del__(self):
        # Restore terminal settings on destruction
        try:
            termios.tcsetattr(sys.stdin, termios.TCSADRAIN, self.old_settings)
        except:
            pass


def main(args=None):
    rclpy.init(args=args)
    
    calibration_tool = ArmCalibrationTool()
    
    try:
        calibration_tool.run()
    finally:
        calibration_tool.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()